apply plugin: 'com.android.library'

android {
    compileSdkVersion 27

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
//    androidTestCompile('com.android.support.test.espresso:espresso-core:3.0.2', {
//        exclude group: 'com.android.support', module: 'support-annotations'
//    })
    api 'com.android.support:appcompat-v7:27.1.1'
//    testCompile 'junit:junit:4.12'

    compileOnly 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    compileOnly "${project.TeslaWeexSDK}"
    compileOnly "com.alibaba:fastjson:${project.fastjsonLibVersion}"
}
